export { default as StartScreen } from './StartScreen'
export { default as LoginScreen } from './LoginScreen'
export { default as RegisterScreen } from './RegisterScreen'
export { default as ForgotPasswordScreen } from './ForgotPasswordScreen'
export { default as Dashboard } from './Dashboard'
export { default as AuthLoadingScreen } from './AuthLoadingScreen'
export { default as ClassIndex } from './ClassIndex'
export { default as QuizIndex } from './QuizIndex'
export { default as CameraIndex } from './CameraIndex'
export { default as ResultScreen } from './ResultScreen'
export { default as StatScreen} from './StatScreen'